# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'url.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import sys
from main import getfile, getfiles
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(890, 470)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(260, 350, 311, 71))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 20, 461, 241))
        self.label.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(550, 270, 91, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(190, 270, 351, 31))
        self.lineEdit.setObjectName("lineEdit")
        # MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton_2.clicked.connect(self.selecionaImagem)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))

    def selecionaImagem(self):
        fname, _ = QtWidgets.QFileDialog.getOpenFileName(parent=self, caption='Select File', directory = QtCore.QDir.currentPath(),
         filter = 'All Files(*.*);; Images (*.jpg; *.png)', initialFilter = 'Images (*.jpg; *.png)')
        imagePath = fname[0]
        pixmap = QPixmap(imagePath)
        self.label.setPixmap(QPixmap(pixmap))

        self.resize(pixmap.width(), pixmap.height())

    def pegarArquivo(self):
           pass
		
    # def getfiles(self):
    #         dlg = QFileDialog()
    #         dlg.setFileMode(QFileDialog.AnyFile)
    #         dlg.setFilter("Text files (*.txt)")
    #         filenames = QStringList()
    #
    #         if dlg.exec_():
    #             filenames = dlg.selectedFiles()
    #             f = open(filenames[0], 'r')
    #
    #             with f:
    #                 data = f.read()
    #                 self.contents.setText(data)
